name = "Sunflower"
license = "MIT"
licenselink = "https://gitlab.com/Ruberhauptmann/sunflower/-/blob/main/LICENSE"
description = "A hugo theme using tailwindcss"


homepage = "https://gitlab.com/Ruberhauptmann/sunflower"
tags = ["Responsive"]
features = []
min_version = "0.88.0"

[author]
  name = "Tjark Sievers"
  homepage = "https://tjarksievers.de"
