theme = "sunflower"
languageCode = "en-us"
baseURL = "https://example.com"
title = "Sunflower Example Site"
ignoreFiles = []

copyright = "Copyright © 2024, Leon N. Cooper, all rights reserved."

[pagination]
  pagerSize = 6

[params]
  favicon = "sunflower.png"
  hero = "hero.jpg"
  profile = "profile.png"
  mainSections = ["projects", "blog"]
  homepageSections = ["posts", "boardgames"]
  abstract = """
    This is a site showing the capacities of the sunflower theme for hugo.
    Using the example of Nobel laureate Leon N. Cooper, it shows the features it specifically has for the needs of academics.
  """
  bgg_title = "Last boardgames played"
  bgg_username = "ourkindofart"

[params.social.orcid]
  link = "#orcid"
[params.social.email]
  link = "#email"
[params.social.github]
  link = "#github"
[params.social.linkedin]
  link = "#linkedin"
[params.social.gpg]
  link = "/gpg.txt"

[params.cv]
  url = "/cv/"
  download = "#cvdownload"
  general = true
  education = true
  work_experience = true
  technical_skills = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[frontmatter]
date = ['date_finished', ':default']

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"

[menu]
[[menu.main]]
  name = "CV"
  url = "/cv"
  weight = -120
[[menu.main]]
  name = "Projects"
  url = "/categories/project-showcases"
  weight = -110
[[menu.main]]
  name = "Lecture Notes"
  url = "/lecture-notes"
  weight = -100
[[menu.main]]
  name = "About"
  url = "/about"
  weight = 0
