theme = "sunflower"
languageCode = "en-us"
baseURL = "https://example.com"
title = "Sunflower Example Site"

author = "Joe Bob"
copyright = "Copyright © 2024, Joe Bob, all rights reserved."

paginate = 3


[params]
  favicon = "sunflower.png"
  hero = "hero.jpg"
  mainSections = ["projects", "blog"]
  abstract = "This is a site showing the capacities of the sunflower theme for hugo."


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[frontmatter]
date = ['date_finished', ':default']


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/categories/project-showcases"
    weight = -140
  [[menu.main]]
    name = "Blog"
    url = "/categories/blog"
    weight = -130
  [[menu.main]]
    name = "Lecture Notes"
    url = "/lecture-notes"
    weight = -120
  [[menu.main]]
    name = "CV"
    url = "/cv"
    weight = -110
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = -100

[params.cv]
  url = "/cv/"
  general = true
  education = true
  work_experience = true
  publications = true
